### ISSUE TITLE
Waste of time editor dont work!

### ISSUE THREAD

**Issue by neil501** [dshook/UnitySaveEditor#5]
I downloaded this opened it up and it is just a folder with some files in it no way to run the editor so this is just a waste of time. Please fix this editor so it can be opened and run. Thank you.

**Comment by GlowingUmbreon** [comment]
This is a unity plugin, it is meant to be used in unity and has no binary file.

**Comment by sophienix** [comment]
it wont work i might be using the worng version of unity i have it where it told me too and i dont see add save editor in add tabs

**Comment by sophienix** [comment]
i got it im just dumb and tried to add it as a tab lol
