### ISSUE TITLE
Error deserializing save: Unable to find 'Assembly-CSharp ...'

### ISSUE THREAD

**Issue by Gnumaru** [dshook/UnitySaveEditor#6]
While trying to deserialize a save file for the game "Astalon: Tears of the Earth", available on steam:

https://store.steampowered.com/app/1046400/Astalon_Tears_of_the_Earth/

I get following error:
![image](https://user-images.githubusercontent.com/5783414/120936229-2c67bc00-c6dd-11eb-869b-2a1ea74252a3.png)
I can confirm this save file is a common .net binary serialized file, as can be seen by inspecting it's contents in a text editor able to view binary files:
![image](https://user-images.githubusercontent.com/5783414/120936266-6a64e000-c6dd-11eb-9c6e-b1bacca5fe97.png)
I'm using unity 2021.1.7f1 to run the save editor, on windows 10 x64. Unfortunately, I don't know which unity version was used to create this game.

I'm also attaching the savefile itself.
I had to zip the save file otherwise GitHub would not let me upload
[0.zip](https://github.com/dshook/UnitySaveEditor/files/6604694/0.zip)

**Comment by dshook** [comment]
The save editor is intended for developers that have the source code for the game.  All the type information is needed to de-serialize and introspect the save file.

**Comment by Gnumaru** [comment]
Well, I should have thought I would need the type definitions.

Deserializing and serializing back the **binary**formater output without the original type definitions is really not a trivial task. Before opening this issue I was using www.saveeditonline.com , which is able to successfully edit the save file, I thought this project could have a similar capability of editing save files without the type definitions.

Just for curiosity's sake, I've searched for means of deserializing and serializing back a binaryformater file and found about the format specification

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nrbf/75b9fe09-be15-475f-85b8-ae7b7558cfe5?redirectedfrom=MSDN

And also found a working python package able to deserialize the binary file into a json file

https://pypi.org/project/netfleece/

I was able to deserialize my save file with the command "python -m netfleece.netfleece -i 0.dat -o 0.json". Unfortunately, it is not able to write back, only reading.

Also found another python reader, but I didn't test it out.

https://github.com/gurnec/Undo_FFG/blob/master/nrbf.py

And also a nuget package, again only for reading

https://www.nuget.org/packages/BinaryFormatDataStructure/

After deserializing my save file with netfleece, I got this json content:
![Screenshot 2021-06-15 092539](https://user-images.githubusercontent.com/5783414/122052447-16808800-cdbc-11eb-9f7e-94b73de0cac0.png)
Which I also attached for anyone interested in giving a look.
[0.dat.json.zip](https://github.com/dshook/UnitySaveEditor/files/6655533/0.dat.json.zip)
